import './globals.css'
import { Metadata } from "next";

export const metadata:Metadata = {
  title: {
    default: 'NEXT.JS TUTORIAL - CODEVOLUTION',
    template: '%s | My App',
  },
  description: 'Generated by next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor: 'lightblue', padding: '10px', textAlign: 'center'}}>
          <h1>Navigation bar</h1>
        </header> 
        {children} 
        <footer style={{backgroundColor: 'lightgray', marginTop: '20px', padding: '10px', textAlign: 'center'}}>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  );
}